### PR TITLE
Add theme: Floating Web Panel

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Floating Web Panel

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Floating Web Panel
* **Description**: Opening the sidebar's web panel will be over the page's content, instead of splitting the space.
* **Homepage**: https://github.com/tunalad/zen-floating-webpanel/
* **Author**: @tunalad

### CODE REVIEW

**Comment by NOCanoa** [comment]
@tunalad 
is this not alredy build it?
image
i dont understand what ur theme is doing

**Comment by tunalad** [comment]
On my end it splits the page in half
Screenshots_2024-08-29_02:41:51
(taken on a clean profile)

**Comment by NOCanoa** [comment]
press here 
image

**Comment by tunalad** [comment]
@NOCanoa Yeah that worked,this theme is redundant then. I assumed that the `_` would just make the window smaller or something. Sorry for that, it's my first time messing with browsers with unorthodox layouts xdd

**Pull request closed without merging**
