### PR TITLE
Add theme: Sidebery

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Sidebery

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Sidebery
* **Description**: Tweaks to support Sidebery as an alternative to Zen's native tabs and workspace implementation.
* **Homepage**: https://github.com/shanto/sidebery
* **Author**: @shanto

### CODE REVIEW

**Comment by shanto** [comment]
Replaces #517

**Comment by mauro-balades** [comment]
Can you add a more simple/smaller image that doesnt also showcase other mods?

**Comment by shanto** [comment]
> Can you add a more simple/smaller image that doesnt also showcase other mods?

Added in #539. Thank you.

**Comment by shanto** [comment]
@mauro-balades Thank you

**Pull request merged**
