### PR TITLE
Add theme: Exit Button Right Padding

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Exit Button Right Padding

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Exit Button Right Padding
* **Description**: A simple theme that adds a bit of padding to the right of the exit button
* **Homepage**: https://github.com/ericmackrodt/zen-themes/
* **Author**: @ericmackrodt

### CODE REVIEW

**Comment by mauro-balades** [comment]
you could use `--zen-element-separation`

**Comment by ericmackrodt** [comment]
I'll updated it

**Comment by ericmackrodt** [comment]
Hi, is there a place that documents all of the --zen css variables?

**Comment by mauro-balades** [comment]
Not really, you could look into `zen-theme.css` in the source code...

**Pull request merged**
