### PR TITLE
Add theme: New tab button below

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: New tab button below

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: New tab button below
* **Description**: Move the new tab button to the end of the list of open tabs
* **Homepage**: https://github.com/Osmagtor/zen-themes/tree/main/New%20tab%20button%20at%20the%20bottom
* **Author**: @Osmagtor

### CODE REVIEW

**Comment by mauro-balades** [comment]
@Osmagtor please provide an image that'll fit on the theme store, checkuot other themes for inspiration. And this should be ready to merge!

**Comment by Osmagtor** [comment]
Sure thing. I hope this one will fit the theme store better.
image

**Comment by Osmagtor** [comment]
Actually, this one is a little wider and might be a better fit.

image2

**Comment by ProbablyM-S** [comment]
this is redundant now I think cuz the new tab button can be placed anywhere starting with a.3 update

**Comment by mauro-balades** [comment]
Sorry @Osmagtor but im currently having some issues, if you could please reopen the PR, that would be great. THanks!

**Pull request closed without merging**
