### PR TITLE
Add theme: Floating toolbar

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Floating toolbar

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Floating toolbar
* **Description**: Detaches toolbar from edge of browser window so that it appears to float
* **Homepage**: 
* **Author**: @anaarkei

### CODE REVIEW

**Comment by dhanushl0l** [comment]
this looks good

**Comment by mauro-balades** [comment]
Why not just use the default compact mode solution along with https://zen-browser.app/themes/d8a9b9a4-30b7-48b5-99ad-448efa604f7e?

**Comment by anaarkei** [comment]
The default compact mode plus the linked theme does not do the same thing from what I can see. In this configuration the toolbar does not appear to be detached from the edge of the browser.

**Comment by ProbablyM-S** [comment]
> Why not just use the default compact mode solution along with https://zen-browser.app/themes/d8a9b9a4-30b7-48b5-99ad-448efa604f7e?

It makes the toolbar floating with rounded corners and it looks really cool, compact only hides the toolbar it makes it floating just like the tab bar, this can even be default imo.

**Comment by mauro-balades** [comment]
Got it

**Pull request merged**
