### PR TITLE
Add theme: Sidebery

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Sidebery

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Sidebery
* **Description**: Collection of several tweaks to support usage of Sidebery as an alternative to Zen's native tabs.
* **Homepage**: https://github.com/shanto/sidebery
* **Author**: @shanto

### CODE REVIEW

**Comment by mauro-balades** [comment]
Please remove the `@-moz-document url-prefix("chrome:")` as it is not needed, thanks!

**Comment by shanto** [comment]
> Please remove the `@-moz-document url-prefix("chrome:")` as it is not needed, thanks!
> 
> Also, how does it differ from https://zen-browser.app/themes/5274f79a-e648-4029-adf3-3f10dfdc0012?

Thank you for your review. It's very different. The original mod only does one thing. It hides Zen's native Tab implementation UI. On the other hand, this mod 1) hides Zen native tabs, 2) allows normal vs collapsed view of the Sidebery sidebar, 3) Allows controlling transparent/semi-transparent background for the sidebar. 4) Contains tweaks to bookmark/history panels and various fixes to make everything look pixel perfect. 5) Hides fully in full-screen mode.

**Comment by n7itro** [comment]
@shanto you could also consider contributing to https://github.com/Alexcoder5/zen-sidebery/
Otherwise, the original Sideberry mod would be obsolete

**Comment by shanto** [comment]
> @shanto you could also consider contributing to https://github.com/Alexcoder5/zen-sidebery/ Otherwise, the original Sideberry mod would be obsolete

I asked in Discord about whether to merge or create now. There, I got replies suggesting creating anew. If you recommend merging, shall I just clone, update and send PR on the original one?

**Comment by TheOverpassArsonist** [comment]
As a suggestion it might be good to make the panel feature of sideberry mirror with the native workspace behaviour of Zen itself, so each panel corresponds to an existing workspace and vice versa. As it is they're disconnected which means both the native tab display (which doesn't seem to get hidden for me even with the setting active) and Sideberry can be hiding different tabs, so tab A might only be visible on the native bar whereas Tab B is only visible on Sideberry.

(also, unrelated to this, but does anyone know how the hell to return to the tab display if you press something like ctrl-h and the history thing comes up? It eats the entire sideberry window for itself and I can't find any way of exiting out of it that doesn't close the sideberry window entirely)

**Pull request closed without merging**
