### PR TITLE
Add theme: Compact Sidebar

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Compact Sidebar

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Compact Sidebar
* **Description**: Allow the tab sidebar to take up less space!
* **Homepage**: https://github.com/n7itro/Zen-Themes/
* **Author**: @n7itro

### CODE REVIEW

**Comment by mauro-balades** [comment]
`uc.sidebar.compact-min-width` is probably not needed as it's what people will primarily install it for, please remove it if you want

**Comment by n7itro** [comment]
I don't have edit permission here. You can remove `uc.sidebar.compact-min-width` 
```css
media (-moz-bool-pref: "zen.view.sidebar-expanded") {  
   #navigator-toolbox {
     --zen-navigation-toolbar-min-width: 115px !important;
  }
}
```

**Comment by mauro-balades** [comment]
Review it and let me know if you want it merged like this

**Review by n7itro — APPROVED** [review]
This looks correct, merge it.

**Pull request merged**
