### PR TITLE
Update Theme: Catppuccin

### PR DESCRIPTION
**Pull request by mohvn**
Adjusted the URL bar color to aesthetically match the background color.

Before:
before

After:
after

### CODE REVIEW

**Comment by mauro-balades** [comment]
Please update the version number too in theme.json

**Comment by mauro-balades** [comment]
Please update the theme version too

**Comment by mohvn** [comment]
> Please update the theme version too

Fixed.

**Comment by mauro-balades** [comment]
Aghh sorry... I haven't realized... You need to change the colors.json as chrome.css is autogenerated... Ill make sure to add support for URL backgrounds and come back later...

**Comment by mohvn** [comment]
> Aghh sorry... I haven't realized... You need to change the colors.json as chrome.css is autogenerated... Ill make sure to add support for URL backgrounds and come back later...

Ok no problem

**Pull request closed without merging**
