### PR TITLE
Add theme: New tab button position

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: New tab button position

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: New tab button position
* **Description**: New tab button position is always the last in order
* **Homepage**: https://github.com/benstone326/zen-browser-new-tab-position/tree/main
* **Author**: @benstone326

### CODE REVIEW

**Comment by sjclayton** [comment]
@benstone326 - I feel this would be better addressed directly by the maintainer as a built-in option... with the additional functionality to choose where the user wants the button positioned or if they want it at all. 

As well the default tab opening behaviour should follow where the button is placed if possible, and not always open at the bottom regardless, as it creates a very weird UX.

**Comment by mohvn** [comment]
There's only a issue that, when we pin a tab, the divider keeps in the button instead of the last pinned tab


legacy mode enabled

**Comment by ProbablyM-S** [comment]
this is the official location now this can be closed.

**Comment by keiothic** [comment]
> this is the official location now this can be closed.

You are saying the new tab icon is to be at the bottom of regular (not pinned) tabs?  Because mine is all the way to the bottom near the sidebar toggle button.  I wish for it to be the way that you describe as it is a long travel to just open a new tab... I'm on a.5
image

**Comment by ProbablyM-S** [comment]
ok yeah nvm I am stupid I read the image wrong sorry I thought the preview image meant that location bc of the margin line

**Comment by benstone326** [comment]
@mauro-balades pls, delete this PR. Can't make it work only with CSS since a5.

**Pull request closed without merging**
