### PR TITLE
[fix] Smaller Compact Mode

### PR DESCRIPTION
**Pull request by n7itro**

### CODE REVIEW

**Comment by n7itro** [comment]
Closes https://github.com/n7itro/Zen-Themes/issues/14

**Comment by sjclayton** [comment]
@n7itro 

I just added the modification you made to my userChrome.css and it seems a margin-top of 12.5vh is still not centered, it seems pushed more towards the bottom with that adjustment applied, like there is slightly more page above the top of the sidebar than there is below it.

I played around a bit and 10.5vh seems like a more accurate center, seems much closer to the positioning that existed when using the mod on 1.0.1-a.5

**Comment by n7itro** [comment]
@sjclayton You are right! Since I usually don't have the top toolbar enabled, I forgot to account for that 😅

**Comment by mauro-balades** [comment]
Is it ready for merge?

**Comment by n7itro** [comment]
Yes.

**Pull request merged**
