### PR TITLE
Bookmark Toolbar Tweaks theme update

### PR DESCRIPTION
**Pull request by n7itro**
Adds expand-on-hover and expand-on-search feature.

### CODE REVIEW

**Comment by n7itro** [comment]
Don't merge yet.

**Comment by mauro-balades** [comment]
Please do test it and tell me if it worked!

**Comment by n7itro** [comment]
I tested it and it _should_ work

**Comment by n7itro** [comment]
The animation is broken. Maybe I need to add `!important`

**Pull request merged**
