### PR TITLE
Add theme: Hide Unified Extensions

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Hide Unified Extensions

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Hide Unified Extensions
* **Description**: You can finally hide the unifiedExtensions button.
* **Homepage**: https://github.com/tangowithfoxtrot/zen-hide-unified-extensions
* **Author**: @tangowithfoxtrot

### CODE REVIEW

**Comment by mauro-balades** [comment]
Could you please remove the settings? If the user wants it removed, they will install the theme or uninstall if not, but there's no need for preferences. Thanks!

**Comment by tangowithfoxtrot** [comment]
I can. Do I need to re-sumbit a PR? I can't edit this one.

**Comment by tangowithfoxtrot** [comment]
I think it may be best to leave the settings toggle. The Unified Extensions button is the only way to pin extensions to the toolbar, and having to uninstall the theme and reinstall it just to do that is frustrating. I'd prefer that we leave the toggle.

**Comment by mauro-balades** [comment]
Thanks!

**Comment by mauro-balades** [comment]
The theme page changed, there's a way to disable with s toggle

**Pull request merged**
