### PR TITLE
Add theme: Nord Theme

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Nord Theme

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Nord Theme
* **Description**: Nord Theme for Zen
* **Homepage**: https://github.com/BennyPLS/zen-nord-theme
* **Author**: @BennyPLS

### CODE REVIEW

**Comment by mauro-balades** [comment]
Should I close this one or the other one?

**Comment by BennyPLS** [comment]
I think i can made some configuration options to accommodate his theme into mine, and take some inspirations, what you think?

PD: Great Browser i wanted to keep using firefox (To try to support alternative browsers) and this is simply great, keep the good job :D.

**Comment by Mircobrb** [comment]
> I think i can made some configuration options to accommodate his theme into mine, and take some inspirations, what you think?
> 
> PD: Great Browser i wanted to keep using firefox (To try to support alternative browsers) and this is simply great, keep the good job :D.

Yeah would be perfect 👌 

(also from me great job guys with Zen, awesome browser👍👍)

**Comment by mauro-balades** [comment]
Sure, dw

**Comment by mauro-balades** [comment]
Im closing this as there seems to be 2 different PRs

**Pull request closed without merging**
