### PR TITLE
Add theme: Wider Zen Sidebar

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Wider Zen Sidebar

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Wider Zen Sidebar
* **Description**: This theme let's you expand the Zen Sidebar even more!
* **Homepage**: 
* **Author**: @Axenide

### CODE REVIEW

**Comment by mauro-balades** [comment]
Hi, you can just change `zen.view.sidebar-expanded.max-width` so I dont really see an use for this, sorry!

**Comment by Axenide** [comment]
Oh, that's even better. Thanks!

**Comment by Axenide** [comment]
`zen.view.sidebar-expanded.max-width` doesn't work, I'll open an issue. 😅

**Comment by Axenide** [comment]
@mauro-balades Hi, sorry to bother you. This actually isn't for the tab sidebar but for the web panels! I just tested `zen.view.sidebar-expanded.max-width` again and noticed the tabs "reloading".

**Comment by mauro-balades** [comment]
Huh, I'll check it out

**Pull request closed without merging**
