### PR TITLE
Add theme: Bigger Mute Button

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Bigger Mute Button

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Bigger Mute Button
* **Description**: Enlarges mute button, hides sound labels, and replaces tab icon with mute button when not expanded.
* **Homepage**: https://github.com/jvabn/zenbrowser-themes
* **Author**: @jvabn

### CODE REVIEW

**Comment by NOCanoa** [comment]
@jvabn when tab bar is compact ,when pressed the Mutte button does it just wasp to the tab or does it mute the tab?

**Comment by jvabn** [comment]
@NOCanoa pressing the mute button when in compact mode will mute the tab. In compact mode, tab with audio playing can be swapped to by clicking part of the tab outside the mute button in the center.

**Comment by mauro-balades** [comment]
Could you provide an image that fits the theme's preview box? Checkout other themes for inspiration

**Comment by jvabn** [comment]
@mauro-balades [Swapped out the image for a new one](https://raw.githubusercontent.com/jvabn/zenbrowser-themes/refs/heads/main/bigger-mute-button/preview.png). Are the dimensions on this one ok?

**Comment by mauro-balades** [comment]
Thanks a lot!

**Pull request merged**
