### PR TITLE
Add theme: Crimson

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Crimson

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Crimson
* **Description**: A crimson red theme for Zen :)
* **Homepage**: 
* **Author**: @shaeriz

### CODE REVIEW

**Comment by shaeriz** [comment]
I don't know how to convert this part of the css to json, so I'd be so glad if someone could add it for me <3 

--toolbar-field-background-color: #772F36 !important;

**Comment by mauro-balades** [comment]
Thanks!

**Comment by mauro-balades** [comment]
> I don't know how to convert this part of the css to json, so I'd be so glad if someone could add it for me <3
> 
> --toolbar-field-background-color: #772F36 !important; --toolbar-field-focus-background-color: #772F36 !important;

This will be handled by zen

**Comment by shaeriz** [comment]
> > I don't know how to convert this part of the css to json, so I'd be so glad if someone could add it for me <3
> > --toolbar-field-background-color: #772F36 !important; --toolbar-field-focus-background-color: #772F36 !important;
> 
> This will be handled by zen

I think it didn't work, it's looking like this 
image

and with that extra css it should look like this, but Idk what to put in the .json file to add it:
image

**Pull request merged**
