### PR TITLE
Add theme: Disable Rounded Corners

### PR DESCRIPTION
**Pull request by mauro-balades**
# Add theme: Disable Rounded Corners

This PR adds a new theme to the theme library.

## Theme Details
* **Name**: Disable Rounded Corners
* **Description**: Disable Rounded Corners from Web View.
* **Homepage**: https://github.com/gunir/desktop/tree/themes/themes
* **Author**: @gunir

### CODE REVIEW

**Comment by mauro-balades** [comment]
Could you provide a better image? It has to bee like 800x600

**Comment by gunir** [comment]
> Could you provide a better image? It has to bee like 800x600. @gunir

True, I made a new one: https://raw.githubusercontent.com/gunir/desktop/themes/themes/image.png

**Comment by n7itro** [comment]
@gunir can you update the commit with the new image

**Comment by mauro-balades** [comment]
Again, the image has to fit in the themes preview box. So it has to be more rectangular

**Comment by n7itro** [comment]
> Again, the image has to fit in the themes preview box. So it has to be more rectangular

It would look better if the page width was larger, and if the image box adapts to the image shape

**Comment by gunir** [comment]
How about this ?
image

**Comment by mauro-balades** [comment]
Property 1=Default(1)

ill just change it to this one

**Comment by gunir** [comment]
> just trying to make the store look professional, hope you dont mind
> 
> image

I like it, I'm not a designer person so even better if I don't have to make preview image.

**Pull request merged**
